### ISSUE TITLE
Functional Error

### ISSUE THREAD

**Issue by Tanmay502** [creepymarshmallow117/booking_app#2]
**BUG Name** : Functional Error
**BUG ID**       : 0001
**AREA PATH**0 : Home > App Drawer
**BUILD NO.**    : Beta 0.01.0v
**ASSIGNED TO** : Gautam Deshpande
**ASSIGNED BY** : Tanmay Devare
**ASSIGNED ON** : 29/4/21
**REASON** : Defect in Code

**Comment by gautam142002** [comment]
Solved
